### PR TITLE
Set Jira and Zendesk as internal development

### PR DESCRIPTION
**Pull request by milospb**
Set Jira and Zendesk as internal development

### CODE REVIEW

**Review by leonidzhaldybin — COMMENTED** [review]
What about ServiceNow HTTP integration? Should it already be displayed to the users?

**Review by mavocitrix — APPROVED** [review]

**Comment by mavocitrix** [comment]
Please also remove LEGACY category from DIP bundles for which we do not have HTTP alternative (Jira + zendesk)

**Comment by milospb** [comment]
SN should be displayed.

**Comment by milospb** [comment]
@mavocitrix done

**Review by mavocitrix — APPROVED** [review]

**Pull request merged**
